export const CONSTANTS = {
  REQUEST_FORMAT: 'application/json',
  RESPONSE_FORMAT: 'application/json',
  MULTI_FORM: 'multipart/form-data',
  REQUEST_POST: 'POST',
  REQUEST_GET: 'GET',
  LANGUAGE_ENGLISH: 'en',
  HASHING_ALGORITHM: "sha256",
  SIGNATURE_KEY: "QD32VdbRuMa0iI0q9q7cH6FIHGcNWGdEZOLyK669",
  WEBSITE_NAME: "JSP Foundation",
  HEADER_MENU_SLUG: "header-menu",
  FOOTER_QUICK_MENU_SLUG: "quick-links-menu",
  FOOTER_OTHER_MENU_SLUG: "other-links-menu",
  FOOTER_BOTTOM_MENU_SLUG: "footer-bottom-menu",
  STATUS_SUCCESS: 'SUC200',
  STATUS_FAILED: 'ERR004',
  X_AUTHORIZATION_TOKEN: `Bearer ${process.env.NEXT_PUBLIC_TOKEN}`,
  X_NETWORK_GUID: process.env.NEXT_PUBLIC_GUID,
};
